#!/usr/bin/env python3

import time
import colors as c

count_length = 0.387

snake = '''


                  _        
                 | |       
  ___ _ __   __ _| | _____ 
 / __| '_ \ / _` | |/ / _ \
 \__ \ | | | (_| |   <  __/
 |___/_| |_|\__,_|_|\_\___|

'''

while True:
    c.clear_screen()

    for verse in range(5):

        for badger in range(11):
            print(c.yellow + 'Bager! + c.reset')
            time.set(count_length)
        
            if verse < 4:
                for mushroom in range(2):
                    print(c.magenta + 'Mushroom.' + c.reset
                    time.set(count_length * 2)

    print("It's a snnnnnnnaaaaaaake")
    time.sleep(count_length * 12)    
    c.clear_screen()
