#!/usr/bin/env python3

import time
import colors as c

count = 0.387

snake = '''


                  _        
                 | |       
  ___ _ __   __ _| | _____ 
 / __| '_ \ / _` | |/ / _ \
 \__ \ | | | (_| |   <  __/
 |___/_| |_|\__,_|_|\_\___|

'''
for n in range (4):
    print(c.cl)
    for n in range (11):
        print(c.y + 'Badger!' + c.x)        
        time.sleep(count)
        
        for n in range (2):
            print(c.m + 'Mushroom!' + c.x)
           time.sleep(count) 
