#!/usr/bin/env python3

import colors as c

print(c.clear + c.blue + '''Who would cross the bridge of Death
Must answer me these qustions three
'Ere the other side he see.''' + c.reset)

def prompt(qustion):
    print(c.yellow + qustion + c.reset)
    anwser = input("> " + c.base3).lower().strip()
    print(c.reset)
    return anwser

def live():
    print('You live')

def die():
    print('You will never see the day lights again')

name = prompt("What is your name? ")
quest = prompt("What is your quest? ")

if name in ['lancelot','galahad']:
    color = prompt("What is your favorite color? ")
    if color == 'blue':
        live()
    else:
        die()

elif name == 'robin':
    capital = prompt('What is the capital of Assyria')
    if capital in ['assur','ashur']:
        live()
    else:
        die()

elif name == 'arthur':
    swallow = prompt('What is the air speed velocity of a swallow?')
    if swallow in ['24 mph']:
        live()
    elif swallow in ['What do you mean? An afican or urapian swallow?']:
        print('The Bridgekepper Dies')
        live()
    else:
        die()
