#!/usr/bin/env python3

import colors as c
from utils import ask

text = '''
THE QUIZ OF DEATH
I love going to {noun1} and doing {verb1}. I also like doing mischief 
like {verb2}. Also I like going to {noun2}. With my friends {person1}
and {person2}.
'''

words = {
    "noun1" : None,
    "noun2" : None,
    "verb1" : None,
    "verb2" : None,
    "person1" : None,
    "person2" : None
}

for key in words:
    words[keyword] = ask("keyword.rstrip('0123456789') + ': ')

print(c.clear + text.format(**words))
