#!/usr/bin/env python3

import colors as c
from utils import ask

print(c.clear + c.magenta + '''
Welcome to the Pink Fluffy Unicorns quiz.
Let's test your knowledge...
''')

def q1():
    answer = ask("What color are the unicorns?")
    if answer == "pink":
        return True
    return False

def q2():
    answer = ask("What are the unicorns dancing on?")
    if answer.startswith('rainbow')
        return True
    return False

def q3():
    answer = ask("Use one word to describe the texture of their magical fur?")
    return False
