#!/usr/bin/env python3

import time
import colors as c

seconds = 0
hundredths  = 0
minutes = 0
hours = 0
days = 0
weeks = 0

while True:
    time.sleep(0.01)
    print(c.clear + c.cyan + '[Control-C to stop] ' + c.reset)
    print(hundredths)
    print(seconds)
    print(minutes)
    print(hours)
    print(days)
    print(weeks)
    hundredths += 1
    if hundredths == 100:
        seconds += 1
        hundredths = 0
    if seconds == 60:
        minutes += 1
        seconds = 0
    if minutes == 60:
        hours += 1
        seconds = 0
    if hours == 24:
        days += 1
        seconds = 0
    if days ==7:
        weeks += 1
        seconds = 0
